<?php

$_COS_LANG_MODULE['blocks_manip_info_description'] = 'Indtast dine stam data, firma, email etc.';
$_COS_LANG_MODULE['blocks_manip_info_value'] = 'Dennis Iversen
Gudrunsvej 70
8210 Brabrand
Danmark
Telefon:
40854015
Email: dennis.iversen@gmail.com
CVR:
22 22 22 22
Jarl & Marianne Schacht';
$_COS_LANG_MODULE['block_manip_label_add_block'] = 'Tilføj Blok';
$_COS_LANG_MODULE['block_manip_form_show_title'] = 'Vis titel';
$_COS_LANG_MODULE['block_manip_confirm_insert'] = 'Blok er tilføjet';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = 'Ret blok';
$_COS_LANG_MODULE['block_manip_confirm_deleted'] = 'Blok blev slettet';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = 'Slet';
$_COS_LANG_MODULE['block_manip_form_error_title'] = 'Indtast titel';
$_COS_LANG_MODULE['block_manip_form_error_content'] = 'Indtast indhold';
$_COS_LANG_MODULE['blocks'] = 'Ventre Blokke';
$_COS_LANG_MODULE['blocks_sec'] = 'Højre blokke';
$_COS_LANG_MODULE['blocks_top'] = 'Top blokke';
$_COS_LANG_MODULE['blocks_buttom'] = 'Bund blokke';
$_COS_LANG_MODULE['blocks_unused'] = 'Ubenyttede blokke';
$_COS_LANG_MODULE['block_manip_sort_success'] = 'Blokkenes orden er blevet gemt';
