<?php

$_COS_LANG_MODULE['block_manip_module_main_title'] = 'Blokke';
$_COS_LANG_MODULE['block_manip_config_description'] = 'Stam Oplysninger';
$_COS_LANG_MODULE['block_manip_menu_sort'] = 'Sorter';
$_COS_LANG_MODULE['block_manip_costum_block_edit'] = 'Vis';
$_COS_LANG_MODULE['block_manip_menu_costum_add'] = 'Tilføj';
$_COS_LANG_MODULE['block_manip_costum_block_list'] = 'Egne Blokke';
$_COS_LANG_MODULE['blocks'] = 'Left blocks';
$_COS_LANG_MODULE['/modules/block_manip/blocks/block_manip_info.inc-human'] = 'Brugerdefineret Block';
