<?php

$_COS_LANG_MODULE['block_manip_sort_success'] = '块的订单已保存';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = '删除块';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = '编辑块';
$_COS_LANG_MODULE['block_manip_label_add_block'] = '添加块';
$_COS_LANG_MODULE['block_manip_form_show_title'] = '显示标题';
$_COS_LANG_MODULE['block_manip_form_error_title'] = '添加标题';
$_COS_LANG_MODULE['block_manip_form_error_content'] = '新增内容';
$_COS_LANG_MODULE['block_manip_confirm_insert'] = '加座';
$_COS_LANG_MODULE['block_manip_confirm_deleted'] = '删除块';
