<?php


// Translation of file /modules/block_manip/module.php

$_COS_LANG_MODULE['block_manip_sort_success'] = 'Block order has been saved';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = 'Delete block';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = 'Edit block';
$_COS_LANG_MODULE['block_manip_label_add_block'] = 'Add block';
$_COS_LANG_MODULE['block_manip_form_show_title'] = 'Show Title';
$_COS_LANG_MODULE['block_manip_form_error_title'] = 'Add title';
$_COS_LANG_MODULE['block_manip_form_error_content'] = 'Add content';

// Translation of file /modules/block_manip/custom/delete.php

$_COS_LANG_MODULE['block_manip_confirm_deleted'] = 'Block deleted';

// Translation of file /modules/block_manip/custom/edit.php

$_COS_LANG_MODULE['block_manip_confirm_insert'] = 'Block added';

// Translation of file /modules/block_manip/custom/add.php
