<?php

$_COS_LANG_MODULE['blocks_manip_info_description'] = 'Base Data, Company, Email etc.';
$_COS_LANG_MODULE['blocks_manip_info_value'] = "Dennis Iversen
Gudrunsvej 70
8210 Brabrand
Danmark
Telefon:
40854015
Email: dennis.iversen@gmail.com
CVR:
22 22 22 22
Jarl & Marianne Schacht";

$_COS_LANG_MODULE['block_manip_label_add_block'] = 'Add block';
$_COS_LANG_MODULE['block_manip_form_show_title'] = 'Show Title';
$_COS_LANG_MODULE['block_manip_confirm_insert'] = 'Block added';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = 'Edit block';
$_COS_LANG_MODULE['block_manip_confirm_deleted'] = 'Block deleted';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = 'Delete block';
$_COS_LANG_MODULE['block_manip_form_error_title'] = 'Add title';
$_COS_LANG_MODULE['block_manip_form_error_content'] = 'Add content';

$_COS_LANG_MODULE['blocks'] = 'Left blocks';
$_COS_LANG_MODULE['blocks_sec'] = 'Right blocks';
$_COS_LANG_MODULE['blocks_top'] = 'Top blocks';
$_COS_LANG_MODULE['blocks_buttom'] = 'Buttom blocks';
$_COS_LANG_MODULE['blocks_unused'] = 'Blocks not used';

$_COS_LANG_MODULE['block_manip_sort_success'] = 'Block order has been saved';
