<?php

$_COS_LANG_MODULE['block_manip_module_main_title'] = 'Blocks';
$_COS_LANG_MODULE['block_manip_config_description'] = 'Base data';
$_COS_LANG_MODULE['block_manip_menu_sort'] = 'Sort';
$_COS_LANG_MODULE['block_manip_costum_block_edit'] = 'Show block';
$_COS_LANG_MODULE['block_manip_menu_costum_add'] = 'Add block';
$_COS_LANG_MODULE['block_manip_costum_block_list'] = 'Custom blocks';
$_COS_LANG_MODULE['blocks'] = 'Blocks';
$_COS_LANG_MODULE['/modules/block_manip/blocks/block_manip_info.inc-human'] = 'Custom Block';
