<?php

$_COS_LANG_MODULE['block_manip_sort_success'] = 'Bestill av blokkene har blitt lagret';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = 'Slett';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = 'Redigere blokk';
$_COS_LANG_MODULE['block_manip_label_add_block'] = 'Legg Block';
$_COS_LANG_MODULE['block_manip_form_show_title'] = 'Vis tittel';
$_COS_LANG_MODULE['block_manip_form_error_title'] = 'Skriv inn tittel';
$_COS_LANG_MODULE['block_manip_form_error_content'] = 'Tast innhold';
$_COS_LANG_MODULE['block_manip_confirm_insert'] = 'Block legges';
$_COS_LANG_MODULE['block_manip_confirm_deleted'] = 'Block ble slettet';
