<?php

$_COS_LANG_MODULE['blocks_manip_info_description'] = 'Skriv inn din herre data, firma, e-post osv.';
$_COS_LANG_MODULE['blocks_manip_info_value'] = 'Dennis Iversen Gudrunsvej 70 8210 Brabrand Danmark Telefon: 40854015 E-post: dennis.iversen @ gmail.com TEL: 22 22 22 22 Earl &amp; Marianne Schacht';
$_COS_LANG_MODULE['block_manip_label_add_block'] = 'Legg Block';
$_COS_LANG_MODULE['block_manip_form_show_title'] = 'Vis tittel';
$_COS_LANG_MODULE['block_manip_confirm_insert'] = 'Block legges';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = 'Redigere blokk';
$_COS_LANG_MODULE['block_manip_confirm_deleted'] = 'Block ble slettet';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = 'Slett';
$_COS_LANG_MODULE['block_manip_form_error_title'] = 'Skriv inn tittel';
$_COS_LANG_MODULE['block_manip_form_error_content'] = 'Tast innhold';
$_COS_LANG_MODULE['blocks'] = 'Ventre Blocks';
$_COS_LANG_MODULE['blocks_sec'] = 'Høyre blokker';
$_COS_LANG_MODULE['blocks_top'] = 'Toppblokker';
$_COS_LANG_MODULE['blocks_buttom'] = 'Bottom blokker';
$_COS_LANG_MODULE['blocks_unused'] = 'Ubrukte blokker';
$_COS_LANG_MODULE['block_manip_sort_success'] = 'Bestill av blokkene har blitt lagret';
