<?php

$_MODULE_MENU[] = array(
        'title' => lang::translate('block_manip_menu_sort'),
        'url' => '/block_manip/sort/index',
        'auth' => 'admin',
);

/**
$_MODULE_MENU[] = array (
    //array(
        'title' => lang::system('block_manip_menu'),
        'url' => '/block_manip/config/index',
        'auth' => 'admin',
    //),

);
**/

$_MODULE_MENU[] = array (
    //array(
        'title' => lang::translate('block_manip_costum_block_list'),
        'url' => '/block_manip/custom/index',
        'auth' => 'admin',
    //),

);