<?php

$_COS_LANG_MODULE['block_manip_confirm_deleted'] = 'Block gelöscht';
$_COS_LANG_MODULE['block_manip_confirm_insert'] = 'Block hinzugefügt';
$_COS_LANG_MODULE['block_manip_sort_success'] = 'Blockauftrag wurde gespeichert';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = 'Block löschen';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = 'Block bearbeiten';
$_COS_LANG_MODULE['block_manip_label_add_block'] = 'Baustein hinzufügen';
$_COS_LANG_MODULE['block_manip_form_show_title'] = 'Titel anzeigen';
$_COS_LANG_MODULE['block_manip_form_error_title'] = 'Titel hinzufügen';
$_COS_LANG_MODULE['block_manip_form_error_content'] = 'Inhalt hinzufügen';
