<?php

$_COS_LANG_MODULE['blocks_manip_info_description'] = 'Anna master data, yritys, sähköposti jne.';
$_COS_LANG_MODULE['blocks_manip_info_value'] = 'Dennis Iversen Gudrunsvej 70 8210 Brabrand Tanska Puhelin: 40854015 Sähköposti: dennis.iversen @ gmail.com TEL: 22 22 22 22 Earl &amp; Marianne Schacht';
$_COS_LANG_MODULE['block_manip_label_add_block'] = 'Lisää Block';
$_COS_LANG_MODULE['block_manip_form_show_title'] = 'Näytä otsikko';
$_COS_LANG_MODULE['block_manip_confirm_insert'] = 'Block lisätään';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = 'Muokkaa lohko';
$_COS_LANG_MODULE['block_manip_confirm_deleted'] = 'Block on poistettu';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = 'Poistaa';
$_COS_LANG_MODULE['block_manip_form_error_title'] = 'Kirjoita otsikko';
$_COS_LANG_MODULE['block_manip_form_error_content'] = 'Anna sisällön';
$_COS_LANG_MODULE['blocks'] = 'Ventre Blocks';
$_COS_LANG_MODULE['blocks_sec'] = 'Oikea lohkot';
$_COS_LANG_MODULE['blocks_top'] = 'Top lohkot';
$_COS_LANG_MODULE['blocks_buttom'] = 'Bottom lohkot';
$_COS_LANG_MODULE['blocks_unused'] = 'Käyttämättömät lohkot';
$_COS_LANG_MODULE['block_manip_sort_success'] = 'Järjestystä lohkojen on tallennettu';
