<?php

$_COS_LANG_MODULE['block_manip_module_main_title'] = 'Blocks';
$_COS_LANG_MODULE['block_manip_config_description'] = 'Perustiedot';
$_COS_LANG_MODULE['block_manip_menu_sort'] = 'Lajitella';
$_COS_LANG_MODULE['block_manip_costum_block_edit'] = 'Näyttää';
$_COS_LANG_MODULE['block_manip_menu_costum_add'] = 'Lisätä';
$_COS_LANG_MODULE['block_manip_costum_block_list'] = 'Treasury Blocks';
$_COS_LANG_MODULE['blocks'] = 'Left blocks';
$_COS_LANG_MODULE['/modules/block_manip/blocks/block_manip_info.inc-human'] = 'Custom Block';
