<?php

$_COS_LANG_MODULE['blocks_manip_info_description'] = 'Base Data, företag, e-post etc.';
$_COS_LANG_MODULE['blocks_manip_info_value'] = 'Dennis Iversen Gudrunsvej 70 8210 Brabrand Danmark Telefon: 40.854.015 Email: dennis.iversen @ gmail.com CVR: 22 22 22 22 Jarl &amp; Marianne Schacht';
$_COS_LANG_MODULE['block_manip_label_add_block'] = 'Lägg blocket';
$_COS_LANG_MODULE['block_manip_form_show_title'] = 'Visa titel';
$_COS_LANG_MODULE['block_manip_confirm_insert'] = 'Block tillsattes';
$_COS_LANG_MODULE['block_manip_label_edit_block'] = 'Redigera blocket';
$_COS_LANG_MODULE['block_manip_confirm_deleted'] = 'Block utgå';
$_COS_LANG_MODULE['block_manip_label_delete_block'] = 'Radera blocket';
$_COS_LANG_MODULE['block_manip_form_error_title'] = 'Lägg till rubrik';
$_COS_LANG_MODULE['block_manip_form_error_content'] = 'Lägg till innehåll';
$_COS_LANG_MODULE['blocks'] = 'Vänster block';
$_COS_LANG_MODULE['blocks_sec'] = 'Right block';
$_COS_LANG_MODULE['blocks_top'] = 'Top block';
$_COS_LANG_MODULE['blocks_buttom'] = 'Buttom block';
$_COS_LANG_MODULE['blocks_unused'] = 'Blockerar inte används';
$_COS_LANG_MODULE['block_manip_sort_success'] = 'Block order har sparats';
