<?php

$_COS_LANG_MODULE['block_manip_module_main_title'] = 'Block';
$_COS_LANG_MODULE['block_manip_config_description'] = 'Basdata';
$_COS_LANG_MODULE['block_manip_menu_sort'] = 'Sortera';
$_COS_LANG_MODULE['block_manip_costum_block_edit'] = 'Visa blocket';
$_COS_LANG_MODULE['block_manip_menu_costum_add'] = 'Lägg blocket';
$_COS_LANG_MODULE['block_manip_costum_block_list'] = 'Anpassade block';
$_COS_LANG_MODULE['blocks'] = 'Left blocks';
$_COS_LANG_MODULE['/modules/block_manip/blocks/block_manip_info.inc-human'] = 'Anpassad Block';
